version: 1.0.{build}
environment:
  matrix:
    - job_name: Windows MSVC build
      appveyor_build_worker_image: Visual Studio 2022

cache:
  - c:\vcpkg -> vcpkg.cmake

init:
  - cmd: >-
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

      git clone https://github.com/microsoft/vcpkg c:\vcpkg

      c:\vcpkg\bootstrap-vcpkg.bat

      set VCPKG_DEFAULT_TRIPLET=x64-windows

build_script:
  - cmd: >-
      cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -B build -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake .

      cmake --build build

test_script:
  - cmd: cd build

      ctest -C debug --extra-verbose

      cd ..
