version: 1.0.{build}
environment:
  matrix:
#  - job_name: Windows MSVC build
#    appveyor_build_worker_image: Visual Studio 2019
#
#  - job_name: Linux GCC build
#    appveyor_build_worker_image: Ubuntu2004
#
  - job_name: Linux Clang build
    appveyor_build_worker_image: Ubuntu2004
for:
  - matrix:
      only:
        - job_name: Linux Clang build 
    init:
      - sh: "#update cmake!\nsudo apt-get update\nsudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget\nwget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null\nsudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'\nsudo apt-get -y update\nsudo apt-get -y install kitware-archive-keyring\nsudo rm /etc/apt/trusted.gpg.d/kitware.gpg\nsudo apt-get -y install cmake\n#update clang++!\n# i386 not available\nsudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'\nsudo add-apt-repository 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main'\n# 11\nsudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'\nsudo add-apt-repository 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'\n# 12\n#sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'\n#sudo add-apt-repository 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'\nwget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -\n# Fingerprint: 6084 F3CF 814B 57C1 CF12 EFD5 15CF 4D18 AF4F 7421\nsudo apt-get -y update\nsudo apt-get -y install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang\n#set clang++ to specific version:\nsudo update-alternatives --remove-all clang\nsudo update-alternatives --remove-all clang++\nsudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 90\nsudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-11 90\nexport CC=clang\nexport CXX=clang++"
    build_script:
      - sh: "mkdir build\ncmake -G \"Ninja Multi-Config\" -B build\nninja -C build"
    test_script:
      - sh: "cd build && ctest -C debug --verbose && cd .."
      
  - matrix:
      only:
        - job_name: Linux GCC build
    init:
      - sh: "sudo update-alternatives --remove-all gcc \nsudo update-alternatives --remove-all g++\nsudo apt-get update\nsudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget\nwget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null\nsudo add-apt-repository ppa:ubuntu-toolchain-r/test\nsudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'\nsudo apt-get -y update\nsudo apt-get -y install gcc-10 g++-10 ninja-build cmake\n#sudo apt-get -y upgrade\nsudo update-alternatives --remove-all gcc\nsudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90\nsudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90\nsudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30\nsudo update-alternatives --set cc /usr/bin/gcc\nsudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30\nsudo update-alternatives --set c++ /usr/bin/g++\nsudo apt -y autoremove\nexport CC=gcc\nexport CXX=g++"
    build_script:
      - sh: "mkdir build\ncmake -G \"Ninja Multi-Config\" -B build\nninja -C build"
    test_script:
      - sh: "cd build && ctest -C debug --verbose && cd .."
  - matrix:
      only:
        - job_name: Windows MSVC build
    build_script:
      - cmd: "mkdir build\ncmake -G \"Visual Studio 16 2019\" -B build\nMSBuild build\\ALL_BUILD.vcxproj"
    test_script:
      - cmd: "cd build\nctest -C debug --verbose\ncd .."